pafsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
urlpatterns = [
    url(r'^admin/',    include(admin.site.urls)),
    url(r'^',          include('series.urls', namespace='series')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^users/',    include('registration.backends.default.urls')),
]

#Server Files in the test environment
if settings.DEBUG:
    urlpatterns.append(url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

series/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #Search Test
    url(r'^search/$',                                       views.search_view.as_view(),   name='search'),
    #General Site
    url(r'^$',                                              views.index,                   name='index'),
    url(r'^about/$',                                        views.about,                   name='about'),
    url(r'^contact/$',                                      views.contact,                 name='contact'),
    #Indexes/Overviews
    url(r'^lectures/$',                                     views.semester_overview,       name='semester_overview'),
    url(r'^speakers/$',                                     views.people_overview,         name='people_overview'),
    #Autocomplete                                                                          
    url(r'^autocomplete/$',                                 views.autocomplete,            name='autocomplete'),
    #Series                                                                                
    url(r'^series/(?P<pk>[0-9]+)/$',                        views.meta_detail.as_view(),   name='meta_detail'),
    url(r'^files/upload/$',                                 views.meta_create.as_view(),   name='meta_create'),
    url(r'^series/(?P<pk>[0-9]+)/edit$',                    views.meta_edit.as_view(),     name='meta_edit'),
    url(r'^series/(?P<pk>[0-9]+)/delete$',                  views.meta_delete.as_view(),   name='meta_delete'),
    #Files                                                                                 
    url(r'^file/(?P<pk>[0-9]+)/$',                          views.upload_detail.as_view(), name='upload_detail'),
    url(r'^series/(?P<pk>[0-9]+)/upload$',                  views.upload_create.as_view(), name='upload_create'),
    url(r'^files/(?P<pk>[0-9]+)/download$',                 views.upload_file,             name='upload_file'),
    url(r'^files/(?P<pk>[0-9]+)/delete$',                   views.upload_delete.as_view(), name='upload_delete'),
    #User                                                                                  
    url(r'^users/profile/(?P<username>[0-9a-zA-Z._\-]+)/$', views.user_detail.as_view(),   name='user_detail'),
    url(r'^users/profile/edit$',                            views.user_edit.as_view(),     name='user_edit'),
    url(r'^users/register/$',                               views.user_register.as_view(), name='registration_register'),
]

series/views.py
#************************************************************************************
#                                      Views
#************************************************************************************
#====================================================================================
#                                  Include stuff
#====================================================================================
import mimetypes, json
from bootstrap3_datetime.widgets         import DateTimePicker
from collections                         import Counter
from django                              import forms
from django.contrib.auth                 import authenticate, login, logout, get_user_model
User = get_user_model()                  
from django.contrib.auth.decorators      import login_required
from django.core.urlresolvers            import reverse
from django.http                         import HttpResponse, HttpResponseRedirect, HttpResponseServerError
from django.shortcuts                    import get_object_or_404, render, redirect
from django.utils                        import timezone
from django.utils.decorators             import method_decorator
from django.views.generic.detail         import DetailView
from django.views.generic.edit           import UpdateView, CreateView, DeleteView, FormView
from django_comments.models              import Comment, ContentType
from haystack.generic_views              import SearchView
from haystack.forms                      import ModelSearchForm
from haystack.query                      import SearchQuerySet
from nocaptcha_recaptcha.fields          import NoReCaptchaField
from registration.backends.default.views import RegistrationView
from .models                             import UserProfile, Upload, Meta
from .registration_form                  import RegistrationFormUniqueEmail
#====================================================================================
#                                    Actual Code
#====================================================================================
#------------------------------------------------------------------------------------
#                                    Search Forms
#------------------------------------------------------------------------------------
class search_form(ModelSearchForm):
    user       = forms.CharField(required=False)
    start_date = forms.DateField(required=False,widget=DateTimePicker(options={'format':'DD. MMM YYYY','pickTime': False}),input_formats = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%d. %b %Y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y'])
    end_date   = forms.DateField(required=False,widget=DateTimePicker(options={'format':'DD. MMM YYYY','pickTime': False}),input_formats = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%d. %b %Y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y'])

    def search(self):
        #First, store the SearchQuerySet received from other processing.
        sqs = super(search_form, self).search()

        if not self.is_valid():
            return self.no_query_found()
        #If we have advanced options, but not query, do a database wide search
        if ( not self.cleaned_data['q']      ) and \
             ( self.cleaned_data['user']        or \
               self.cleaned_data['start_date']  or \
               self.cleaned_data['start_date'] ):
            sqs = SearchQuerySet().all()
        elif not self.cleaned_data['q']:
            return self.no_query_found()
        #Check to see if a user was chosen.
        if self.cleaned_data['user']:
            sqs = sqs.filter(user__contains=self.cleaned_data['user'])
        #Check to see if a start_date was chosen.
        if self.cleaned_data['start_date']:
            sqs = sqs.filter(date__gte=self.cleaned_data['start_date'])
        #Check to see if an end_date was chosen.
        if self.cleaned_data['end_date']:
            sqs = sqs.filter(date__lte=self.cleaned_data['end_date'])
        
        #Cleaning up Results (Get rid of doubles mainly)
        sqs2 = []
        if not self.cleaned_data['models'] or 'series.userprofile' in self.cleaned_data['models']:
            users = Counter()
            for each in sqs.models(UserProfile).values_list('user_pk'):
                if each[0] is not None:
                    users[each[0]] += 1
            for each in users:
                sqs2.append(sqs.models(UserProfile).filter(user_pk=each).latest('date'))
        if not self.cleaned_data['models'] or 'django_comments.comment' in self.cleaned_data['models']:
            comments = Counter()
            for each in sqs.models(Comment).values_list('comment_pk'):
                if each[0] is not None:
                    comments[each[0]] += 1
            for each in comments:
                sqs2.append(sqs.models(Comment).filter(comment_pk=each).latest('date'))
        if not self.cleaned_data['models'] or 'series.upload' in self.cleaned_data['models']:
            metas = Counter()
            for each in sqs.models(Upload).values_list('meta_pk'):
                if each[0] is not None:
                    metas[each[0]] += 1
            for each in metas:
                sqs2.append(sqs.models(Upload).filter(meta_pk=each).latest('date'))
        return sqs2
class search_view(SearchView):
    form_class = search_form
    template_name = 'search/search.html'
    def get_context_data(self, *args, **kwargs):
        context = super(search_view, self).get_context_data(*args, **kwargs)
        #Check if we have advanced option, and open the form container if we do
        if self.request.GET.get('user','')       != '' or \
           self.request.GET.get('start_date','') != '' or \
           self.request.GET.get('end_date','')   != '':
            context['advanced'] = True
        else:
            context['advanced'] = False
        return context
#------------------------------------------------------------------------------------
#                                    General Site
#------------------------------------------------------------------------------------
def index(request):
    context = {
                   'user_num'    : User.objects.all().count(),
                   'upload_num'  : Upload.objects.all().count(),
                   'meta_num'    : Meta.objects.all().count(),
                   'comment_num' : Comment.objects.all().count(),
              }
    return render(request, 'webpage/index.html', context)
def about(request):
    return render(request, 'webpage/about.html')
def contact(request):
    return render(request, 'webpage/contact.html')
#------------------------------------------------------------------------------------
#                                     Overviews
#------------------------------------------------------------------------------------
def semester_overview(request):
    semester_list  = [ entry['semester']  for entry in Meta.objects.all().values('semester').order_by('-semester').distinct()]
    programme_list = [ entry['programme'] for entry in Meta.objects.all().values('programme').order_by('-programme').distinct()]
    grid = {}
    for semester in semester_list:
        grid[semester]  = {}
    for semester in semester_list:
        for programme in programme_list:
            lecture_list = [ entry['lecture'] for entry in Meta.objects.filter(semester=semester).filter(programme=programme).values('lecture').order_by('-lecture').distinct()]
            if len(lecture_list)>0:
                grid[semester][programme] = lecture_list
    context = {'grid':grid}
    return render(request, 'overview/semester.html', context)
def people_overview(request):
    year_list      = [ entry['year']      for entry in Meta.objects.all().values('year').order_by('-year').distinct()]
    programme_list = [ entry['programme'] for entry in Meta.objects.all().values('programme').order_by('-programme').distinct()]
    grid = {}
    for year in year_list:
        grid[year]  = {}
    for year in year_list:
        for programme in programme_list:
            lecturer_list = [ entry['lecturer'] for entry in Meta.objects.filter(year=year).filter(programme=programme).values('lecturer').order_by('-lecturer').distinct()]
            if len(lecturer_list)>0:
                grid[year][programme] = lecturer_list
    context = {'grid':grid}
    return render(request, 'overview/people.html', context)
#------------------------------------------------------------------------------------
#                                      Series
#------------------------------------------------------------------------------------
#....................................................................................
#                                   Detail View
#....................................................................................
class upload_detail(DetailView):
    model         = Upload
    template_name = 'uploads/detail.html'
    def get_context_data(self, **kwargs):
        context = super(upload_detail, self).get_context_data(**kwargs)
        context['more_like_this']  = SearchQuerySet().more_like_this(self.get_object()).models(Upload)[:5]
        return context
class meta_detail(DetailView):
    model         = Meta
    template_name = 'metas/detail.html'
    def get_context_data(self, **kwargs):
        context = super(meta_detail, self).get_context_data(**kwargs)
        context['upload_latest']   = Upload.objects.filter(meta=self.get_object()).order_by('-date').first()
        context['upload_authors']  = [ upload['author']   for upload in Upload.objects.filter(meta=self.get_object()).order_by('author').values('author').distinct()    ]
        context['upload_uploader'] = [ User.objects.get(pk=upload['uploader']) for upload in Upload.objects.filter(meta=self.get_object()).order_by('uploader').values('uploader').distinct()]

series/templates/webpage/about.html
{% extends "base.html" %}

{% block site_title %}About{% endblock %}
{% block title %}About{% endblock %}

{% block content %}
	{% lorem 2 p %}
	<h3>Programming</h3>
	{% lorem 2 p %}
	<h3>Licensing</h3>
	{% lorem 2 p %}
	<h3>Disclaimer</h3>
	{% lorem 2 p %}
{% endblock %}

series/templates/webpage/contact.html
{% extends "base.html" %}

{% block site_title %}Contact{% endblock %}
{% block title %}Contact{% endblock %}

{% block content %}
	{% lorem 4 p %}
{% endblock %}

series/templates/webpage/footer.html
<p>Series - Liblist II - Sponsored by PAF</p>
<address>
	Fachschaft &middot; Musterstraße 1a &middot; 01234 Musterhausen<br/>
	Telefon: 999999 &middot; Mail: <a href="mailto:max.mustermann@uni-jena.de">Max Mustermann</a>
</address>
<p>All rights reserved.</p>

series/templates/webpage/generic_form_fields.html
{% load bootstrap %}
{% csrf_token %}
{% for field in form %}
	{{ field|bootstrap }}
{% endfor %}

series/templates/webpage/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block javascript %}
	{{ block.super }}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autoid='#id_q' autoshow='true' %}
{% endblock %}

{% block header %}
	<div class="hidden-lg hidden-md hidden-sm">
		 {{ block.super }}
	</div>
{% endblock %}

{% block page %}
	<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
		<div class="hidden-xs">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<div id="mycarousel" class="carousel slide" data-ride="carousel">
								<!-- Indicators -->
								<ol class="carousel-indicators">
									<li data-target="#mycarousel" data-slide-to="0" class="active"></li>
									<li data-target="#mycarousel" data-slide-to="1"></li>
									<li data-target="#mycarousel" data-slide-to="2"></li>
								</ol>
								<!-- Wrapper for slides -->
								<div class="carousel-inner" role="listbox">
									<div class="item active">
										<img src="{% static 'series/_MG_1652.jpg' %}" alt="Campus">
										<div class="container">
											<div class="carousel-caption">
												<h1>Welcome</h1>
												{% lorem 1 p %}
											</div>
										</div>
									</div>
									<div class="item">
										<img src="{% static 'series/_MG_3157.jpg' %}" alt="Paradies">
										<div class="container">
											<div class="carousel-caption">
												<h1>Welcome</h1>
												{% lorem 1 p %}
											</div>
										</div>
									</div>
									<div class="item">
										<img src="{% static 'series/_MG_3291.jpg' %}" alt="JenTower">
										<div class="container">
											<div class="carousel-caption">
												<h1>Welcome</h1>
												{% lorem 1 p %}
											</div>
										</div>
									</div>
								</div>
								<!-- Controls -->
								<a class="left carousel-control" href="#mycarousel" role="button" data-slide="prev">
									<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
									<span class="sr-only">Previous</span>
								</a>
								<a class="right carousel-control" href="#mycarousel" role="button" data-slide="next">
									<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
									<span class="sr-only">Next</span>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row"><br/></div>
		</div>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<form class="autocomplete-me" method="get" action="{% url 'series:search' %}">
					<div class="panel panel-default">
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									<div class="form-group">
										<label class="control-label " for="id_q">Find Something!</label>
										<input id="id_q" class="ui-autocomplete-input form-control" type="search" name="q" autocomplete="off" placeholder="Search..."/>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									<div class="hidden-lg hidden-md hidden-sm">
										<button type="submit" class="btn btn-primary btn-block">
											<span class="glyphicon glyphicon-open" aria-hidden="true"></span>
											Search
										</button>
									</div>
									<div class="hidden-xs">
										<button type="submit" class="btn btn-primary center-block">
											<span class="glyphicon glyphicon-open" aria-hidden="true"></span>
											Search
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
		<div class="row"><br/></div>
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
					<h4>User: <span class="badge">{{ user_num }}</span></h4>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					<h4>Comments: <span class="badge">{{ comment_num }}</span></h4>
				</div>
				<div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
					<h4>Uploads: <span class="badge">{{ upload_num }}</span></h4>
				</div>
			</div>
		</div>
		<div class="row"><br/></div>
		<div class="row"><br/></div>
	</div>
{% endblock %}

series/templates/webpage/menu.html
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navigation">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'series:index'   %}">Home</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="main-navigation">
			<ul class="nav navbar-nav">
			{% block navigation %}
				<ul class="nav navbar-nav hidden-xs">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
							Indexes
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="{% url 'series:semester_overview' %}">Lectures</a></li>
							<li><a href="{% url 'series:people_overview' %}">Speakers</a></li>
						</ul>
					</li>
				</ul>
				<li class="xs-only"><a href="{% url 'series:semester_overview' %}">Lectures</a></li>
				<li class="xs-only"><a href="{% url 'series:people_overview' %}">Speakers</a></li>
				<li><a href="{% url 'series:search' %}">Search</a></li>
				<li><a href="{% url 'series:about'   %}">About</a></li>
				<li><a href="{% url 'series:contact' %}">Contact</a></li>
				<li><a href="{% url 'series:meta_create' %}">Upload</a></li>
			{% endblock %}
			</ul>
			{% if user.is_authenticated %}
				<ul class="nav navbar-nav navbar-right hidden-xs">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
							{% if user.get_short_name == '' %}
								Welcome {{ user.get_username }}
							{% else %}
								Welcome {{ user.get_short_name }}
							{% endif %}
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="{% url 'series:user_detail' user.username %}">Profile </a></li>
							<li><a href="{% url 'series:user_edit' %}#">Edit Profile</a></li>
							<li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
							{% if user.is_staff %}
								<li><a href="{% url 'admin:index' %}">Administration</a></li>
							{% endif %}
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'auth_logout' %}?next={{request.path}}">Logout</a></li>
						</ul>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right hidden-sm hidden-md hidden-lg">
					<li role="separator" class="divider"></li>
					<li><a href="{% url 'series:user_detail' user.username %}">Profile</a></li>
					<li><a href="{% url 'series:user_edit' %}#">Edit Profile</a></li>
					<li><a href="{% url 'auth_password_change' %}#">Change Password</a></li>
					{% if user.is_staff %}
						<li><a href="{% url 'admin:index' %}">Administration</a></li>
					{% endif %}
					<li role="separator" class="divider"></li>
					<li><a href="{% url 'auth_logout' %}?next={{request.path}}">Logout</a></li>
				</ul>
			{% else %}
				<ul class="nav navbar-nav navbar-right">
					<li><a class="hidden-sm hidden-md hidden-lg" href="{% url 'auth_login' %}?next={{request.path}}">Login</a></li>
					<li><a href="{% url 'registration_register' %}">Register</a></li>
				</ul>
				<form class="navbar-form navbar-right hidden-xs hidden-sm" action="{% url 'auth_login' %}?next={{request.path}}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<input type="text"     id="username" name="username" class="form-control" placeholder="Username" maxlength=30 />
						<input type="password" id="password" name="password" class="form-control" placeholder="Password" maxlength=50 />
					</div>
					<button type="submit" class="btn btn-default">Login</button>
				</form>
				<div class="navbar-form navbar-right hidden-xs hidden-md hidden-lg">
					<a class="btn btn-default" role="button" href="{% url 'auth_login' %}?next={{request.path}}">Login</a>
				</div>
			{% endif %}
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>