pafsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
urlpatterns = [
    url(r'^admin/',    include(admin.site.urls)),
    url(r'^',          include('series.urls', namespace='series')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^users/',    include('registration.backends.default.urls')),
]

#Server Files in the test environment
if settings.DEBUG:
    urlpatterns.append(url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

series/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #Search Test
    url(r'^search/$',                                       views.search_view.as_view(),   name='search'),
    #General Site
    url(r'^$',                                              views.index,                   name='index'),
    url(r'^about/$',                                        views.about,                   name='about'),
    url(r'^contact/$',                                      views.contact,                 name='contact'),
    #Indexes/Overviews
    url(r'^lectures/$',                                     views.semester_overview,       name='semester_overview'),
    url(r'^speakers/$',                                     views.people_overview,         name='people_overview'),
    #Autocomplete                                                                          
    url(r'^autocomplete/$',                                 views.autocomplete,            name='autocomplete'),
    #Series                                                                                
    url(r'^series/(?P<pk>[0-9]+)/$',                        views.meta_detail.as_view(),   name='meta_detail'),
    url(r'^files/upload/$',                                 views.meta_create.as_view(),   name='meta_create'),
    url(r'^series/(?P<pk>[0-9]+)/edit$',                    views.meta_edit.as_view(),     name='meta_edit'),
    url(r'^series/(?P<pk>[0-9]+)/delete$',                  views.meta_delete.as_view(),   name='meta_delete'),
    #Files                                                                                 
    url(r'^file/(?P<pk>[0-9]+)/$',                          views.upload_detail.as_view(), name='upload_detail'),
    url(r'^series/(?P<pk>[0-9]+)/upload$',                  views.upload_create.as_view(), name='upload_create'),
    url(r'^files/(?P<pk>[0-9]+)/download$',                 views.upload_file,             name='upload_file'),
    url(r'^files/(?P<pk>[0-9]+)/delete$',                   views.upload_delete.as_view(), name='upload_delete'),
    #User                                                                                  
    url(r'^users/profile/(?P<username>[0-9a-zA-Z._\-]+)/$', views.user_detail.as_view(),   name='user_detail'),
    url(r'^users/profile/edit$',                            views.user_edit.as_view(),     name='user_edit'),
    url(r'^users/register/$',                               views.user_register.as_view(), name='registration_register'),
]

series/models.py
#************************************************************************************
#                                     Models
#************************************************************************************
#====================================================================================
#                                  Include stuff
#====================================================================================
import datetime, os, re, mimetypes
from django.conf                import settings
from django.contrib.auth.models import User
from django.db                  import models
from django.templatetags.static import static
from django.utils               import timezone
from reversion                  import revisions as reversion
from series.pdf2txt             import pdf2txt
from .validators                import validate_mimetype, validate_filesize
#====================================================================================
#                                    Actual Code
#====================================================================================
#------------------------------------------------------------------------------------
#                                     Uploads
#------------------------------------------------------------------------------------
@reversion.register #Save History
class Upload(models.Model):
    #Meta
    meta         = models.ForeignKey('Meta',null=True)
    #The File
    file         = models.FileField(validators   = [validate_filesize, validate_mimetype],
                                    upload_to    = 'series',
                                    verbose_name = 'File Selection',
                                    help_text    = 'Only PDF, TXT, and TEX files smaller than 5MB.',
                                    )
    #Original Filename
    filename = models.CharField(max_length = 250,
                                default  = '',
                                editable = False,
                                )
    #Upload date
    date         = models.DateTimeField(verbose_name = 'Upload Date',
                                        default      = timezone.now,
                                        )
    #Uploader
    uploader     = models.ForeignKey(User,
                                     verbose_name = 'Uploader',
                                     null = True,
                                    )
    #Show only for logged in users?
    login_only   = models.BooleanField(default      = True,
                                       verbose_name = 'Login required',
                                       help_text    = 'Require login for downloading the file.',
                                       )
    #Author of the document
    author   = models.CharField(max_length   = 50,
                                default      = '',
                                verbose_name = 'Author',
                                help_text    = 'Here belongs the author of this file. Probably you.',
                                )
    #Type of the document
    CONTENT_TYPE_CHOICES = ( ('Exercise', (
                                              ('Ea', 'Exercise (without a Solution in it)'),
                                              ('EA', 'Exercise with Solution'),
                                          )
                             ),
                             ('Exam',     (
                                              ('Ta', 'Exam (without a Solution in it)'),
                                              ('TA', 'Exam with Solution'),
                                          )
                             ),
                             ('Script',   (
                                              ('s', 'Script approved by the Lecturer'),
                                              ('S', 'Unapproved Script'),
                                          )
                             ),
                             ('Solution', (
                                              ('ea', 'Solution to an Exercise'),
                                              ('ta', 'Solution to an Exam/Test'),
                                          )
                             ),
                           )
    content_type = models.CharField(max_length = 2,
                                    choices    = CONTENT_TYPE_CHOICES,
                                    default    = 'E',
                                    verbose_name = 'Content Type of the Upload',
                                    )
    #Downloads
    downloads       = models.PositiveIntegerField(default = 0,editable    = False)
    #Content Extract
    content         = models.TextField(default = '',editable    = False)
    #More Meta-Information is saved and connected with the Meta Model
    def file_content_extract(self):
        #Get Filetype
        mime = mimetypes.guess_type(self.file.name)[0]
        #Extract Data
        if   mime == 'application/pdf':
            try:
                content = pdf2txt(self.file.file).read()
            except:
                content = ''
        elif mime == 'text/plain' or mime == 'application/x-tex':
            self.file.open()
            content = self.file.read().decode('utf-8')
        else:
            #Don't know how to extract!!
            return
        #Cleanup Data
        content = re.sub('[\W_]',' ',content)
        content = re.sub('[\s]+',' ',content)
        #Save Extract
        self.content = content
    def __str__(self):
        return self.filename
    def get_filetype(self):
        return os.path.splitext(self.file.path)[1][1:].upper()
    def get_filesize(self):
        suffixes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB']
        back = '0 B'
        nbytes = self.file.size*1.
        if nbytes > 0.:
            i = 0
            while nbytes >= 1024. and i < len(suffixes)-1:
                nbytes /= 1024.
                i += 1
            back = '{size:.2f} {suffix}'.format(size = nbytes, suffix = suffixes[i])
        return back
#------------------------------------------------------------------------------------
#                                    Meta Data
#------------------------------------------------------------------------------------
#This class is for saving all Meta Data, which has to be put in by the User.
#------------------------------------------------------------------------------------
@reversion.register #Save History
class Meta(models.Model):
    #Name of the File
    name         = models.CharField(max_length = 50,
                                    default    = '',
                                    help_text  = 'Enter a meaningful name, to make this file easier to find.',
                                    )
    #Description
    description  = models.TextField(default   = '',
                                    help_text = 'Enter a short description of the files content. This is what people will see, if not logged in.',
                                    )
    #Keywords
    keywords     = models.TextField(default   = '',
                                    help_text = 'Enter a set of keywords describing the content. Make it short and proper!',
                                    )
    #Title of the lecture
    lecture      = models.CharField(max_length   = 50,
                                    default      = '',
                                    verbose_name = 'Lecture',
                                    help_text    = 'Enter the lecture which this file belongs to.',
                                    )
    #Lecturer/Speaker/Tutor/Professor
    lecturer     = models.CharField(max_length   = 50,
                                    default      = '',
                                    verbose_name = 'Speaker',
                                    help_text    = 'The speaker/tutor/instructor of said lecture.',
                                    )
    #Year of the Lecture
    year            = models.SmallIntegerField(default = datetime.datetime.now().year)
    #Semester in which the lecture belongs
    SEMESTER_CHOICES = ( ( 1, '1. Semester'),
                         ( 2, '2. Semester'),
                         ( 3, '3. Semester'),
                         ( 4, '4. Semester'),
                         ( 5, '5. Semester'),
                         ( 6, '6. Semester'),
                         ( 7, '7. Semester'),
                         ( 8, '8. Semester'),
                         ( 9, '9. Semester'),
                         ( 10, '10. Semester'),)
    semester = models.SmallIntegerField(choices   = SEMESTER_CHOICES,
                                        default   = 1,
                                        help_text = 'Graduate Level of the Lecture.',
                                        )
    #Programme the lecture belongs to
    programme = models.CharField(max_length   = 50,
                                 default      = '',
                                 verbose_name = 'Graduation Course',
                                 help_text    = 'Graduation Course the lecture belongs to. (e.g. Bachelor of Science in Physics)',
                                 )
    #Area of Physics
    area         = models.CharField(max_length   = 50,
                                    default      = '',
                                    verbose_name = 'Area of the Lecture',
                                    help_text    = '(e.g. Optics)'
                                    )
    def clean_keywords(self):
        self.keywords = re.sub('[\W_]',' ',self.keywords)
        self.keywords = re.sub('[\s]+',' ',self.keywords)
    def save(self, *args, **kwargs):
        self.clean_keywords()
        super(Meta, self).save(*args, **kwargs)
    def __str__(self):
        return self.name
    def keywords_as_list(self):
        return self.keywords.split()
    def get_latest_upload(self):
        return Upload.objects.filter(meta=self).order_by('-date').first()

series/templates/metas/create.html
{% extends "metas/edit_base.html" %}
{% block title %}All your Files are belong to us!{% endblock %}
{% block site_title %}Upload{% endblock %}

{% block editformurl %}{% url 'series:meta_create' %}{% endblock %}
{% block editbutton %}
	{% with "Upload" as editbuttonname %}
		{{ block.super }}
	{% endwith %}
{% endblock %}

series/templates/metas/delete.html
{% extends "base.html" %}

{% block title %}Delete <em>{{ meta.name }}</em>?{% endblock %}
{% block site_title %}Delete - {{ meta.name }}{% endblock %}

{% block alert %}
	{% if form.errors %}
	<div class="alert alert-danger" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<p>Error while submitting the form. Please check your input, and try again.</p>
	</div>
	{% endif %}
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<form action="{% url 'series:meta_delete' meta.id %}" method="POST">
				<p>The series, all its upload, as well as all its comments will be deleted, a recovery is not possible.</p>
				<p>Are you sure you want to delete <strong>{{ meta.name }}</strong>?</p>
				{% include 'webpage/generic_form_fields.html' %}
				<div class="row"><br/></div>
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="hidden-lg hidden-md hidden-sm">
							<button class="btn btn-danger btn-block" type="submit" value="delete">
								<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
								Delete
							</button>
							<a href="{% url 'series:meta_detail' meta.id %}" class="btn btn-default btn-block" type="submit">
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
								Cancel
							</a>
						</div>
						<div class="hidden-xs">
							<button class="btn btn-danger" type="submit" value="delete">
								<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
								Delete
							</button>
							<a href="{% url 'series:meta_detail' meta.id %}" class="btn btn-default" type="submit">
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
								Cancel
							</a>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

series/templates/metas/detail_bar.html
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="hidden-lg hidden-md hidden-sm">
			<a class="btn btn-warning btn-block {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:upload_create' meta.id %}">
				<span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>
				Add File
			</a>
			<a class="btn btn-primary btn-block {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:meta_edit' meta.id %}">
				<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
				Edit
			</a>
			<a class="btn btn-danger btn-block {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:meta_delete' meta.id %}">
				<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
				Delete
			</a>
			<a class="btn btn-success btn-block {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:upload_file' upload_latest.id %}">
				<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
				Download
			</a>
		</div>
		<div class="hidden-xs">
			<a class="btn btn-warning {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:upload_create' meta.id %}">
				<span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>
				Add File
			</a>
			<a class="btn btn-primary {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:meta_edit' meta.id %}">
				<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
				Edit
			</a>
			<a class="btn btn-danger {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:meta_delete' meta.id %}">
				<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
				Delete
			</a>
			<a class="btn btn-success {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:upload_file' upload_latest.id %}">
				<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
				Download
			</a>
		</div>
	</div>
</div>

series/templates/metas/detail_labels.html
{% load comments %}
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="h4">
			<a href="{% url 'series:search' %}?q={{ meta.lecture|urlencode }}"><span class="label label-primary label-spaced"><span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span> {{ meta.lecture }}</span></a>
			<a href="{% url 'series:search' %}?q={{ meta.lecturer|urlencode }}"><span class="label label-primary label-spaced"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ meta.lecturer }}</span></a>
			<a href="{% url 'series:search' %}?q={{ meta.year|urlencode }}"><span class="label label-primary label-spaced"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> {{ meta.year }}</span></a>
			<a href="{% url 'series:search' %}?q={{ meta.area|urlencode }}"><span class="label label-success label-spaced"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> {{ meta.area }}</span></a>
			<a href="{% url 'series:search' %}?q={{ meta.programme|urlencode }}"><span class="label label-primary label-spaced"><span class="glyphicon glyphicon-road" aria-hidden="true"></span> {{ meta.programme }}</span></a>
			<a href="{% url 'series:search' %}?q={{ meta.get_semester_display|urlencode }}"><span class="label label-primary label-spaced"><span class="glyphicon glyphicon-road" aria-hidden="true"></span> {{ meta.get_semester_display }}</span></a>
			<span class="label label-default label-spaced"><span class="glyphicon glyphicon-open" aria-hidden="true"></span> {{ meta.upload_set.count }} Uploads</span>
			{% get_comment_count for series.meta meta.id as comment_count %}
			<span class="label label-default label-spaced"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> {{ comment_count }} Comments</span>
		</div>
	</div>
</div>

series/templates/metas/discussion.html
{% load comments %}
{% load bootstrap %}
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="page-header">
			<h2 id="discussion">Discussion</h2>
		</div>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				{% get_comment_count for series.meta meta.id as comment_count %}
				<p>{{ comment_count }} Comments</p>
				{% get_comment_list for series.meta meta.id as comment_list %}
				{% for comment in comment_list %}
					{% include 'metas/discussion_comment.html' %}
				{% endfor %}
			</div>
		</div>
		<div class="row hidden-lg hidden-md hidden-sm"><br/></div>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				{% if user.is_authenticated %}
					{% get_comment_form for meta as form %}
					<form action="{% comment_form_target %}" method="POST">
						{% csrf_token %}
						{{ form.comment|bootstrap }}
						{{ form.honeypot }}
						{{ form.content_type }}
						{{ form.object_pk }}
						{{ form.timestamp }}
						{{ form.security_hash }}
						<input type="hidden" name="next" value="{% url 'series:meta_detail' meta.id %}" />
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
								<div class="hidden-lg hidden-md hidden-sm">
									<button type="submit" class="btn btn-block btn-primary" value="Post">
										<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
										Submit Comment
									</button>
								</div>
								<div class="hidden-xs">
									<button type="submit" class="btn btn-primary pull-right" value="Post">
										<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
										Submit Comment
									</button>
								</div>
							</div>
						</div>
					</form>
				{% else %}
					<p>Please <a href="{% url 'auth_login' %}?next={% url 'series:meta_detail' meta.id %}">log in</a> to leave a comment.</p>
				{% endif %}
			</div>
		</div>
	</div>
</div>

series/templates/metas/discussion_comment.html
<div class="row">
	<div class="col-lg-2 col-md-2 col-sm-2 hidden-xs">
		<div class="row">
			<div class="col-lg-10 col-lg-offset-2 col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2">
				<a href="{% url 'series:user_detail' comment.user.get_username %}"><span class="thumbnail"><img src="{{ comment.user.userprofile.get_image_url }}" alt="{{ comments.user.get_username }}" height="150"/></span></a>
			</div>
		</div>
	</div>
	<div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>
				<ol class="commentcrumb">
				<li><a href="{% url 'series:meta_detail' comment.object_pk %}">{{ comment.content_object }}</a></li>
				<li><a href="{% url 'series:user_detail' comment.user.get_username %}">{{ comment.user.get_username }}</a></li>
				</ol>
				</strong>
				<strong class="pull-right">{{ comment.submit_date }}</strong>
			</div>
			<div class="panel-body">
				<p>{{ comment.comment }}</p>
			</div>
		</div>
	</div>
</div>

series/templates/metas/edit.html
{% extends "metas/edit_base.html" %}
{% block title %}Edit: {{ meta.name }}{% endblock %}
{% block site_title %}{{ meta.name }} - Edit{% endblock %}

{% block editformurl %}{% url 'series:meta_edit' meta.id %}{% endblock %}
{% block fileinfo %}{% endblock %}
{% block editbutton %}
	{% with "Save" as editbuttonname %}
		{{ block.super }}
	{% endwith %}
{% endblock %}

series/templates/metas/edit_base.html
{% extends "base.html" %}
{% load bootstrap %}

{% block alert %}
	{% if form.errors %}
	<div class="alert alert-danger" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<p>Error while submitting the form. Please check your input, and try again.</p>
	</div>
	{% endif %}
{% endblock %}

{% block javascript %}
	{{ block.super }}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autocategory='people'    autoid='#id_author' %}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autocategory='lecture'   autoid='#id_lecture' %}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autocategory='people'    autoid='#id_lecturer' %}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autocategory='keywords'  autoid='#id_keywords' %}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autocategory='area'      autoid='#id_area' %}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autocategory='programme' autoid='#id_programme' %}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autocategory='metaname'  autoid='#id_name' %}
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<form action="{% block editformurl %}{% endblock %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingName">
						<h2 class="panel-title">
							<a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseName" aria-expanded="true" aria-controls="collapseName">
							Name
							</a>
						</h2>
					</div>
					<div id="collapseName" class="panel-collapse collapse in" role="tab" aria-labelledby="headingName">
						<div class="panel-body">
							{{ form.name|bootstrap }}
						</div>
					</div>
				</div>
				{% block fileinfo %}
					{% include 'uploads/create_form.html' %}
				{% endblock %}
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingDescription">
						<h2 class="panel-title">
							<a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseDescription" aria-expanded="true" aria-controls="collapseDescription">
							Description
							</a>
						</h2>
					</div>
					<div id="collapseDescription" class="panel-collapse collapse in" role="tab" aria-labelledby="headingDescription">
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									{{ form.description|bootstrap }}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingKeywords">
						<h2 class="panel-title">
							<a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseKeywords" aria-expanded="true" aria-controls="collapseKeywords">
							Keywords
							</a>
						</h2>
					</div>
					<div id="collapseKeywords" class="panel-collapse collapse in" role="tab" aria-labelledby="headingKeywords">
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									{{ form.keywords|bootstrap }}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingLectureInfo">
						<h2 class="panel-title">
							<a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseLectureInfo" aria-expanded="true" aria-controls="collapseLectureInfo">
							Lecture Information
							</a>
						</h2>
					</div>
					<div id="collapseLectureInfo" class="panel-collapse collapse in" role="tab" aria-labelledby="headingLectureInfo">
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
									{{ form.lecture|bootstrap }}
								</div>
								<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
									{{ form.lecturer|bootstrap }}
								</div>
							</div>
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
									{{ form.year|bootstrap }}
								</div>
								<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
									{{ form.area|bootstrap }}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingProgrammeInfo">
						<h2 class="panel-title">
							<a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseProgrammeInfo" aria-expanded="true" aria-controls="collapseProgrammeInfo">
							Programme Information
							</a>
						</h2>
					</div>
					<div id="collapseProgrammeInfo" class="panel-collapse collapse in" role="tab" aria-labelledby="headingProgrammeInfo">
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
									{{ form.programme|bootstrap }}
								</div>
								<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
									{{ form.semester|bootstrap }}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
						{{ form.captcha|bootstrap }}
					</div>
				</div>
				{% block editbutton %}
				<div class="hidden-lg hidden-md hidden-sm">
					<div class="row">
						<div class="col-xs-12">
							<button type="submit" class="btn btn-primary btn-block">
								<span class="glyphicon glyphicon-open" aria-hidden="true"></span>
								{{ editbuttonname }}
							</button>
						</div>
					</div>
				</div>
				<div class="hidden-xs">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12">
							<button type="submit" class="btn btn-primary">
								<span class="glyphicon glyphicon-open" aria-hidden="true"></span>
								{{ editbuttonname }}
							</button>
						</div>
					</div>
				</div>
				{% endblock %}
			</form>
		</div>
	</div>
{% endblock %}

series/templates/metas/upload_detail.html
<table class="table">
	<thead>
		<tr>
			<th class="hidden-lg hidden-md">File</th>
			<th class="hidden-xs hidden-sm">File</th>
			<th>Author</th>
			<th>Date</th>
			<th class="hidden-xs hidden-sm">Uploader</th>
			<th>Download</th>
		</tr>
	</thead>
	<tbody>
		{% for upload in upload_list %}
		<tr>
			<td class="hidden-lg hidden-md"><a href="{% url 'series:upload_detail' upload.pk %}">{{ upload|truncatechars:50 }}</a></td>
			<td class="hidden-xs hidden-sm"><a href="{% url 'series:upload_detail' upload.pk %}">{{ upload }}</a></td>
			<td>{{ upload.author }}</td>
			<td>{{ upload.date|date:"d. M Y" }}</td>
			<td class="hidden-xs hidden-sm"><a href="{% url 'series:user_detail' upload.uploader %}">{{ upload.uploader }}</a></td>
			<td>
				<a class="btn btn-success btn-xs {% if not user.is_authenticated and upload.login_only %}disabled{% endif %}" role="button" href="{% url 'series:upload_file' upload.id %}">
					<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
					Download
				</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>