pafsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
urlpatterns = [
    url(r'^admin/',    include(admin.site.urls)),
    url(r'^',          include('series.urls', namespace='series')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^users/',    include('registration.backends.default.urls')),
]

#Server Files in the test environment
if settings.DEBUG:
    urlpatterns.append(url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

series/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #Search Test
    url(r'^search/$',                                       views.search_view.as_view(),   name='search'),
    #General Site
    url(r'^$',                                              views.index,                   name='index'),
    url(r'^about/$',                                        views.about,                   name='about'),
    url(r'^contact/$',                                      views.contact,                 name='contact'),
    #Indexes/Overviews
    url(r'^lectures/$',                                     views.semester_overview,       name='semester_overview'),
    url(r'^speakers/$',                                     views.people_overview,         name='people_overview'),
    #Autocomplete                                                                          
    url(r'^autocomplete/$',                                 views.autocomplete,            name='autocomplete'),
    #Series                                                                                
    url(r'^series/(?P<pk>[0-9]+)/$',                        views.meta_detail.as_view(),   name='meta_detail'),
    url(r'^files/upload/$',                                 views.meta_create.as_view(),   name='meta_create'),
    url(r'^series/(?P<pk>[0-9]+)/edit$',                    views.meta_edit.as_view(),     name='meta_edit'),
    url(r'^series/(?P<pk>[0-9]+)/delete$',                  views.meta_delete.as_view(),   name='meta_delete'),
    #Files                                                                                 
    url(r'^file/(?P<pk>[0-9]+)/$',                          views.upload_detail.as_view(), name='upload_detail'),
    url(r'^series/(?P<pk>[0-9]+)/upload$',                  views.upload_create.as_view(), name='upload_create'),
    url(r'^files/(?P<pk>[0-9]+)/download$',                 views.upload_file,             name='upload_file'),
    url(r'^files/(?P<pk>[0-9]+)/delete$',                   views.upload_delete.as_view(), name='upload_delete'),
    #User                                                                                  
    url(r'^users/profile/(?P<username>[0-9a-zA-Z._\-]+)/$', views.user_detail.as_view(),   name='user_detail'),
    url(r'^users/profile/edit$',                            views.user_edit.as_view(),     name='user_edit'),
    url(r'^users/register/$',                               views.user_register.as_view(), name='registration_register'),
]

series/models.py
#************************************************************************************
#                                     Models
#************************************************************************************
#====================================================================================
#                                  Include stuff
#====================================================================================
import datetime, os, re, mimetypes
from django.conf                import settings
from django.contrib.auth.models import User
from django.db                  import models
from django.templatetags.static import static
from django.utils               import timezone
from reversion                  import revisions as reversion
from series.pdf2txt             import pdf2txt
from .validators                import validate_mimetype, validate_filesize
#====================================================================================
#                                    Actual Code
#====================================================================================
#------------------------------------------------------------------------------------
#                                     Uploads
#------------------------------------------------------------------------------------
@reversion.register #Save History
class Upload(models.Model):
    #Meta
    meta         = models.ForeignKey('Meta',null=True)
    #The File
    file         = models.FileField(validators   = [validate_filesize, validate_mimetype],
                                    upload_to    = 'series',
                                    verbose_name = 'File Selection',
                                    help_text    = 'Only PDF, TXT, and TEX files smaller than 5MB.',
                                    )
    #Original Filename
    filename = models.CharField(max_length = 250,
                                default  = '',
                                editable = False,
                                )
    #Upload date
    date         = models.DateTimeField(verbose_name = 'Upload Date',
                                        default      = timezone.now,
                                        )
    #Uploader
    uploader     = models.ForeignKey(User,
                                     verbose_name = 'Uploader',
                                     null = True,
                                    )
    #Show only for logged in users?
    login_only   = models.BooleanField(default      = True,
                                       verbose_name = 'Login required',
                                       help_text    = 'Require login for downloading the file.',
                                       )
    #Author of the document
    author   = models.CharField(max_length   = 50,
                                default      = '',
                                verbose_name = 'Author',
                                help_text    = 'Here belongs the author of this file. Probably you.',
                                )
    #Type of the document
    CONTENT_TYPE_CHOICES = ( ('Exercise', (
                                              ('Ea', 'Exercise (without a Solution in it)'),
                                              ('EA', 'Exercise with Solution'),
                                          )
                             ),
                             ('Exam',     (
                                              ('Ta', 'Exam (without a Solution in it)'),
                                              ('TA', 'Exam with Solution'),
                                          )
                             ),
                             ('Script',   (
                                              ('s', 'Script approved by the Lecturer'),
                                              ('S', 'Unapproved Script'),
                                          )
                             ),
                             ('Solution', (
                                              ('ea', 'Solution to an Exercise'),
                                              ('ta', 'Solution to an Exam/Test'),
                                          )
                             ),
                           )
    content_type = models.CharField(max_length = 2,
                                    choices    = CONTENT_TYPE_CHOICES,
                                    default    = 'E',
                                    verbose_name = 'Content Type of the Upload',
                                    )
    #Downloads
    downloads       = models.PositiveIntegerField(default = 0,editable    = False)
    #Content Extract
    content         = models.TextField(default = '',editable    = False)
    #More Meta-Information is saved and connected with the Meta Model
    def file_content_extract(self):
        #Get Filetype
        mime = mimetypes.guess_type(self.file.name)[0]
        #Extract Data
        if   mime == 'application/pdf':
            try:
                content = pdf2txt(self.file.file).read()
            except:
                content = ''
        elif mime == 'text/plain' or mime == 'application/x-tex':
            self.file.open()
            content = self.file.read().decode('utf-8')
        else:
            #Don't know how to extract!!
            return
        #Cleanup Data
        content = re.sub('[\W_]',' ',content)
        content = re.sub('[\s]+',' ',content)
        #Save Extract
        self.content = content
    def __str__(self):
        return self.filename
    def get_filetype(self):
        return os.path.splitext(self.file.path)[1][1:].upper()
    def get_filesize(self):
        suffixes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB']
        back = '0 B'
        nbytes = self.file.size*1.
        if nbytes > 0.:
            i = 0
            while nbytes >= 1024. and i < len(suffixes)-1:
                nbytes /= 1024.
                i += 1
            back = '{size:.2f} {suffix}'.format(size = nbytes, suffix = suffixes[i])
        return back
#------------------------------------------------------------------------------------
#                                    Meta Data
#------------------------------------------------------------------------------------
#This class is for saving all Meta Data, which has to be put in by the User.
#------------------------------------------------------------------------------------
@reversion.register #Save History
class Meta(models.Model):
    #Name of the File
    name         = models.CharField(max_length = 50,
                                    default    = '',
                                    help_text  = 'Enter a meaningful name, to make this file easier to find.',
                                    )
    #Description
    description  = models.TextField(default   = '',
                                    help_text = 'Enter a short description of the files content. This is what people will see, if not logged in.',
                                    )
    #Keywords
    keywords     = models.TextField(default   = '',
                                    help_text = 'Enter a set of keywords describing the content. Make it short and proper!',
                                    )
    #Title of the lecture
    lecture      = models.CharField(max_length   = 50,
                                    default      = '',
                                    verbose_name = 'Lecture',
                                    help_text    = 'Enter the lecture which this file belongs to.',
                                    )
    #Lecturer/Speaker/Tutor/Professor
    lecturer     = models.CharField(max_length   = 50,
                                    default      = '',
                                    verbose_name = 'Speaker',
                                    help_text    = 'The speaker/tutor/instructor of said lecture.',
                                    )
    #Year of the Lecture
    year            = models.SmallIntegerField(default = datetime.datetime.now().year)
    #Semester in which the lecture belongs
    SEMESTER_CHOICES = ( ( 1, '1. Semester'),
                         ( 2, '2. Semester'),
                         ( 3, '3. Semester'),
                         ( 4, '4. Semester'),
                         ( 5, '5. Semester'),
                         ( 6, '6. Semester'),
                         ( 7, '7. Semester'),
                         ( 8, '8. Semester'),
                         ( 9, '9. Semester'),
                         ( 10, '10. Semester'),)
    semester = models.SmallIntegerField(choices   = SEMESTER_CHOICES,
                                        default   = 1,
                                        help_text = 'Graduate Level of the Lecture.',
                                        )
    #Programme the lecture belongs to
    programme = models.CharField(max_length   = 50,
                                 default      = '',
                                 verbose_name = 'Graduation Course',
                                 help_text    = 'Graduation Course the lecture belongs to. (e.g. Bachelor of Science in Physics)',
                                 )
    #Area of Physics
    area         = models.CharField(max_length   = 50,
                                    default      = '',
                                    verbose_name = 'Area of the Lecture',
                                    help_text    = '(e.g. Optics)'
                                    )
    def clean_keywords(self):
        self.keywords = re.sub('[\W_]',' ',self.keywords)
        self.keywords = re.sub('[\s]+',' ',self.keywords)
    def save(self, *args, **kwargs):
        self.clean_keywords()
        super(Meta, self).save(*args, **kwargs)
    def __str__(self):
        return self.name
    def keywords_as_list(self):
        return self.keywords.split()
    def get_latest_upload(self):
        return Upload.objects.filter(meta=self).order_by('-date').first()

series/templates/uploads/create.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}Add File to: {{ meta.name }}{% endblock %}
{% block site_title %}{{ meta.name }} - Add File{% endblock %}

{% block javascript %}
	{{ block.super }}
	{% include "search/autocomplete_function.html" with autourl='series:autocomplete' autocategory='people'    autoid='#id_author' %}
{% endblock %}

{% block alert %}
	{% if form.errors %}
	<div class="alert alert-danger" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<p>Error while submitting the form. Please check your input, and try again.</p>
	</div>
	{% endif %}
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<form action="{% url 'series:upload_create' meta.id %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{% include 'uploads/create_form.html' %}
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
						{{ form.captcha|bootstrap }}
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="hidden-lg hidden-md hidden-sm">
							<button type="submit" class="btn btn-primary btn-block">
								<span class="glyphicon glyphicon-open" aria-hidden="true"></span>
								Upload
							</button>
						</div>
						<div class="hidden-xs">
							<button type="submit" class="btn btn-primary">
								<span class="glyphicon glyphicon-open" aria-hidden="true"></span>
								Upload
							</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

series/templates/uploads/create_form.html
{% load bootstrap %}
<div class="panel panel-default">
	<div class="panel-heading" role="tab" id="headingFileInfo">
		<h2 class="panel-title">
			<a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFileInfo" aria-expanded="true" aria-controls="collapseFileInfo">
			File Information
			</a>
		</h2>
	</div>
	<div id="collapseFileInfo" class="panel-collapse collapse in" role="tab" aria-labelledby="headingFileInfo">
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					{{ form.file|bootstrap }}
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					{{ form.author|bootstrap }}
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					{{ form.content_type|bootstrap }}
				</div>
			</div>
		</div>
	</div>
</div>

series/templates/uploads/delete.html
{% extends "base.html" %}

{% block title %}Delete <em>{{ upload }}</em>?{% endblock %}
{% block site_title %}Delete - {{ upload }}{% endblock %}

{% block alert %}
	{% if form.errors %}
	<div class="alert alert-danger" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<p>Error while submitting the form. Please check your input, and try again.</p>
	</div>
	{% endif %}
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<form action="{% url 'series:upload_delete' upload.id %}" method="POST">
				<p>The file will be deleted, a recovery is not possible.</p>
				<p>If this is the last file of a series, the whole entry (with all its comments) will be deleted too.</p>
				<p>Are you sure you want to delete <strong>{{ upload }}</strong>?</p>
				{% include 'webpage/generic_form_fields.html' %}
				<div class="row"><br/></div>
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="hidden-lg hidden-md hidden-sm">
							<button class="btn btn-danger btn-block" type="submit" value="delete">
								<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
								Delete
							</button>
							<a href="{% url 'series:upload_detail' upload.id %}" class="btn btn-default btn-block" type="submit">
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
								Cancel
							</a>
						</div>
						<div class="hidden-xs">
							<button class="btn btn-danger" type="submit" value="delete">
								<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
								Delete
							</button>
							<a href="{% url 'series:upload_detail' upload.id %}" class="btn btn-default" type="submit">
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
								Cancel
							</a>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

series/templates/uploads/detail.html
{% extends "base.html" %}
{% load bootstrap %}

{% block site_title %}{{ upload }} - Detail{% endblock %}
{% block title %}{{ upload }}{% endblock %}

{% block alert %}
	{% if not user.is_authenticated  and upload.login_only %}
	<div class="alert alert-info" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<p>Please <a href="{% url 'auth_login' %}?next={{request.path}}" class="alert-link">login</a> to download.</p>
	</div>
	{% endif %}
{% endblock %}

{% block content %}
	{% include 'uploads/detail_labels.html' %}
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="hidden-lg hidden-md hidden-sm">
				<a class="btn btn-danger {% if not user.is_authenticated %}disabled{% endif %} btn-block" role="button" href="{% url 'series:upload_delete' upload.id %}">
					<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
					Delete
				</a>
				<a class="btn btn-success {% if not user.is_authenticated %}disabled{% endif %} btn-block" role="button" href="{% url 'series:upload_file' upload.id %}">
					<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
					Download
				</a>
			</div>
			<div class="hidden-xs">
				<a class="btn btn-danger {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:upload_delete' upload.id %}">
					<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
					Delete
				</a>
				<a class="btn btn-success {% if not user.is_authenticated %}disabled{% endif %}" role="button" href="{% url 'series:upload_file' upload.id %}">
					<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
					Download
				</a>
			</div>
		</div>
	</div>
	<div class="row"><br/></div>
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="panel panel-default">
				<div class="panel-heading" role="tab" id="headingUploadInfo">
					<h2 class="panel-title">
						<a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseUploadInfo" aria-expanded="true" aria-controls="collapseUploadInfo">
						Upload
						</a>
					</h2>
				</div>
				<div id="collapseUploadInfo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingUploadInfo">
					<div class="panel-body">
						<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
							<h4>Series:</h4>
							<p><a href="{% url 'series:meta_detail' upload.meta.pk %}">{{ upload.meta }}</a></p>
						</div>
						<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
							<h4>Author:</h4>
							<p>{{ upload.author }}</p>
						</div>
						<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
							<h4>Uploader:</h4>
							<p><a href="{% url 'series:user_detail' upload.uploader %}">{{ upload.uploader }}</a></p>
						</div>
						<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
							<h4>Uploader date:</h4>
							<p>{{ upload.date }}</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="page-header">
				<h2 id="similar">Similar</h2>
			</div>
			{% for result in more_like_this %}
				{{ result.rendered|safe }}
			{% endfor %}
		</div>
	</div>
{% endblock %}

series/templates/uploads/detail_labels.html
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="h4">
			{% if upload.login_only %}
				<a href="{% url 'series:search' %}?q=Restricted"><span class="label label-danger label-spaced"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> Restricted</span></a>
			{% else %}
				<a href="{% url 'series:search' %}?q=Public"><span class="label label-success label-spaced"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span> Public</span></a>
			{% endif %}
			<a href="{% url 'series:search' %}?q={{ upload.author|urlencode }}"><span class="label label-primary label-spaced"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ upload.author }}</span></a>
			<a href="{% url 'series:search' %}?q={{ upload.uploader|urlencode }}"><span class="label label-primary label-spaced"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ upload.uploader }}</span></a>
			<a href="{% url 'series:search' %}?q={{ upload.get_content_type_display|urlencode }}"><span class="label label-primary label-spaced"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> {{ upload.get_content_type_display }}</span></a>
			<span class="label label-default label-spaced"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> {{ upload.get_filesize }}</span>
			<span class="label label-default label-spaced"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> {{ upload.get_filetype }}</span>
			<span class="label label-default label-spaced"><span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span> {{ upload.downloads }} Downloads</span>
		</div>
	</div>
</div>